export const basketData = [
    {
        id: 1,
        name: 'Футболка UZcotton мужская',
        img: 'assets/images/t-shirt.png',
        characters: ['Цвет: белый', 'Размер: 56'],
        company: 'ООО Вайлдберриз',
        location: 'Коледино WB',
        price: 1051,
        sale: 50.3,
        checked:false,
        count:1,
        remains:3,
    },
    {
        id: 2,
        name: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
        img: 'assets/images/case.png',
        characters: ['Цвет: прозрачный'],
        company: 'OOO Мегапрофстиль',
        location: 'Коледино WB',
        price: 11500.235,
        sale: 8.7,
        checked:false,
        count:1,
        remains:300,
    },
    {
        id: 3,
        name: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные,<br>Faber-Castell',
        img: 'assets/images/pencils.png',
        characters: [],
        company: 'ООО Вайлдберриз',
        location: 'Коледино WB',
        price: 475,
        sale: 50,
        checked:false,
        count:1,
        remains:3,
    },
]