export const basketData = [
    {
        id: 1,
        name: 'Футболка UZcotton мужская',
        img: 'assets/images/t-shirt.png',
        missingImg:'assets/images/missing-t-shirt.png',
        characters: ['Цвет: белый', 'Размер: 56'],
        company: 'ООО Вайлдберриз',
        location: 'Коледино WB',
        price: 1051,
        sale: 50.3,
        checked:false,
        count:1,
        remains:3,
    },
    {
        id: 2,
        name: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
        img: 'assets/images/case.png',
        missingImg:'assets/images/missing-case.png',
        characters: ['Цвет: прозрачный'],
        company: 'OOO Мегапрофстиль',
        location: 'Коледино WB',
        price: 11500.235,
        sale: 8.7,
        checked:false,
        count:1,
        remains:300,
    },
    {
        id: 3,
        name: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные,<br>Faber-Castell',
        img: 'assets/images/pencils.png',
        missingImg:'assets/images/missing-pencils.png',
        characters: [],
        company: 'ООО Вайлдберриз',
        location: 'Коледино WB',
        price: 475,
        sale: 50,
        checked:false,
        count:1,
        remains:3,
    },
];

export const payMethodslist = [
    {id:1,img:'assets/icons/mir-pay.png',cardNumber:'1234 56•• •••• 1234'},
    {id:2,img:'assets/icons/visa.svg',cardNumber:'1234 56•• •••• 1234'},
    {id:3,img:'assets/icons/master-card.svg',cardNumber:'1234 56•• •••• 1234'},
    {id:4,img:'assets/icons/maestro.svg',cardNumber:'1234 56•• •••• 1234'},
]